# Generated by Django 5.1.3 on 2024-11-22 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCategory',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('createdon', models.DateTimeField(auto_now_add=True, db_column='CreatedOn', verbose_name='CreatedOn')),
                ('modifiedon', models.DateTimeField(auto_now=True, db_column='ModifiedOn', verbose_name='ModifiedOn')),
                ('createdby', models.CharField(db_column='CreatedBy', max_length=100, verbose_name='CreatedBy')),
                ('modifiedby', models.CharField(blank=True, db_column='ModifiedBy', max_length=100, null=True, verbose_name='ModifiedBy')),
                ('isactive', models.BooleanField(db_column='IsActive', verbose_name='IsActive')),
                ('name', models.CharField(db_column='Name', max_length=20, verbose_name='Name')),
                ('description', models.CharField(blank=True, db_column='Description', max_length=1000, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Report Category',
                'verbose_name_plural': 'Report Category',
                'db_table': 'Report"."ReportCategory',
                'managed': False,
            },
        ),
    ]
